# Generated by Django 4.2.2 on 2023-06-17 21:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('porcetagem_agua', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem de água')),
                ('distancia', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Distância')),
                ('abriga_vida', models.CharField(choices=[('INC', 'Incerta'), ('PRO', 'Provável'), ('IMP', 'Improvável')], max_length=3, verbose_name='Abriga vida')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('planeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='planeta.planeta', verbose_name='Planeta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
